#
#  ESP32-S3 Board Configuration
#  Waveshare ESP32-S3-RS485-CAN
#  Flash: 16MB, PSRAM: OPI PSRAM
#

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
  variant: esp32s3
  flash_size: 16MB
  
psram:
  mode: octal
  speed: 80MHz
